const loginPanel=document.querySelector('#loginPanel'),adminPanel=document.querySelector('#adminPanel'),loginStatus=document.querySelector('#loginStatus'),uploadStatus=document.querySelector('#uploadStatus'),records=document.querySelector('#records');let token=sessionStorage.getItem('chenAdminToken')||'';
async function api(url,options={}){const headers=new Headers(options.headers||{});if(token)headers.set('Authorization','Bearer '+token);const response=await fetch(url,{...options,headers});if(response.status===401){logout();throw new Error('登入已逾時，請重新登入')}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||'操作失敗')}return response.status===204?null:response.json()}
function showAdmin(){loginPanel.hidden=true;adminPanel.hidden=false;loadRecords()}
function logout(){token='';sessionStorage.removeItem('chenAdminToken');adminPanel.hidden=true;loginPanel.hidden=false}
loginForm.onsubmit=async event=>{event.preventDefault();loginStatus.textContent='登入中…';try{const result=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:password.value})});token=result.token;sessionStorage.setItem('chenAdminToken',token);password.value='';loginStatus.textContent='';showAdmin()}catch(error){loginStatus.textContent=error.message}};
logout.onclick=logout;
uploadForm.onsubmit=async event=>{event.preventDefault();uploadButton.disabled=true;uploadStatus.textContent='正在上傳與擷取內容，較大的論文可能需要一些時間…';try{await api('/api/knowledge',{method:'POST',body:new FormData(uploadForm)});uploadForm.reset();uploadStatus.textContent='上傳完成，公開智庫已更新。';loadRecords()}catch(error){uploadStatus.textContent=error.message}finally{uploadButton.disabled=false}};
async function loadRecords(){try{const list=await api('/api/knowledge');records.innerHTML=list.length?list.map(item=>`<div class="record"><div><b>${escapeHtml(item.title)}</b><p>${escapeHtml(item.fileName||'')}・${new Date(item.createdAt).toLocaleString('zh-TW')}</p></div><button data-id="${item.id}">刪除</button></div>`).join(''):'<p class="empty">目前還沒有從後台上傳的資料。</p>';records.querySelectorAll('button').forEach(button=>button.onclick=async()=>{if(!confirm('確定刪除這筆知識與原始檔案？'))return;await api('/api/knowledge/'+button.dataset.id,{method:'DELETE'});loadRecords()})}catch(error){uploadStatus.textContent=error.message}}
function escapeHtml(value=''){const node=document.createElement('div');node.textContent=value;return node.innerHTML}
if(token)showAdmin();
