let knowledge=[
{cat:'management',tag:'蜂群管理',title:'蜂箱多久檢查一次？',keys:['多久','檢查','開箱','蜂箱'],text:'一般可每 5～7 天開箱檢查一次；大泌蜜期前或自然分蜂繁殖期，王台容易出現，可縮短為 3～5 天。選天晴溫暖的上午，檢查蜂王、王台、卵蟲圈、粉蜜存量與病蟲害。',source:'農業部養蜂技術問答',url:'https://kmweb.moa.gov.tw/subject/subject.php?id=12637'},
{cat:'management',tag:'蜂群管理',title:'如何選擇養蜂場？',keys:['蜂場','場地','選擇','位置','地點'],text:'先看周邊蜜粉源與鄰近作物用藥。場地宜背風向陽、平坦不積水、車輛可達、有乾淨水源，並避開污染源、住家與夜間燈光。定地蜂場之間最好保持適當距離。',source:'農業部養蜂技術問答',url:'https://kmweb.moa.gov.tw/subject/subject.php?id=12637'},
{cat:'management',tag:'蜂群管理',title:'蜜蜂如何補助餵食？',keys:['餵食','補餵','糖漿','飼料','花粉'],text:'補餵需依季節、蜂勢與存糧調整。早春可用獎勵餵飼協助繁殖，缺蜜粉期除糖漿外也要留意蛋白質來源。避免在採收商品蜜時不當餵糖，並保持餵飼器具清潔。',source:'農業部養蜂技術問答',url:'https://kmweb.moa.gov.tw/subject/subject.php?id=12637'},
{cat:'management',tag:'蜂群管理',title:'如何判斷失王或工蜂產卵？',keys:['失王','蜂王','多粒卵','工蜂產卵','王台'],text:'可查看巢房是否有新卵、幼蟲及正常產卵圈。失王過久可能出現一個巢房多粒卵、卵在房壁且排列凌亂；這通常是工蜂產卵。處理前應綜合王台、蜂勢與聲音判斷。',source:'農業部養蜂技術問答',url:'https://kmweb.moa.gov.tw/subject/subject.php?id=12637'},
{cat:'health',tag:'健康防疫',title:'巢門前突然大量死蜂或吐舌',keys:['死蜂','死亡','大量','中毒','農藥','抽搐','吐舌','舌頭伸出','吻伸出','伸舌'],text:'短時間大量死亡、抽搐、失去方向，以及死蜂的吻（俗稱舌頭）伸出，都是疑似農藥中毒時可觀察的線索。先戴手套採集新鮮蜂屍並依通報單位指示保存，記錄時間、天氣及鄰近施藥情形，再聯絡農政或防疫單位。吐舌並非農藥中毒特有症狀，病毒、其他毒物或非特異狀況也可能出現，不能只靠外觀確診，仍需檢體與農藥分析。',source:'農業部蜜蜂中毒資料／蜜蜂疾病鑑別文獻',url:'https://kmweb.moa.gov.tw/theme_data.php?id=54755&sub_theme=variety&theme=news'},
{cat:'health',tag:'健康防疫',title:'蜂蟹蟎與病蟲害怎麼看？',keys:['蜂蟹蟎','蟹蟎','病蟲害','翅膀','病毒'],text:'爬蜂增加、翅膀變形、蜂勢持續衰弱時，需檢查成蜂、幼蟲、巢脾及蜂蟹蟎量。多種病原症狀可能重疊，應先檢測與諮詢，再依法選擇處置，避免自行濫用藥物。',source:'本機智慧蜂箱研究整理',url:'#death'},
{cat:'honey',tag:'蜂蜜知識',title:'蜂蜜結晶還能吃嗎？',keys:['結晶','變質','硬','白色'],text:'結晶是天然蜂蜜中葡萄糖形成晶體的物理現象，不等於摻假或變質；速度受蜜源與溫度影響。若香氣、顏色正常且保存良好，通常可食用。想恢復流動可連瓶以溫水緩慢回溫，避免高溫。',source:'台灣養蜂協會',url:'https://www.bee.org.tw/Message/ImageList?catalogId=e3ae64cc-6e80-41d8-9d42-6be65e90ee4a'},
{cat:'honey',tag:'蜂蜜知識',title:'如何分辨真假蜂蜜？',keys:['真假','純蜂蜜','螞蟻','分辨','假蜜'],text:'滴水、螞蟻、燃燒等民間方法都不足以判定真假。選擇來源清楚、標示完整、具檢驗或評鑑紀錄的產品；精確判定仍需依蜂蜜國家標準與實驗室分析。',source:'台灣養蜂協會／陳家蜂蜜',url:'https://www.bee.org.tw/Message/ImageList?catalogId=e3ae64cc-6e80-41d8-9d42-6be65e90ee4a'},
{cat:'ecology',tag:'蜜蜂生態',title:'工蜂一生做哪些工作？',keys:['工蜂','工作','任務','採蜜'],text:'工蜂會隨日齡換工作：清潔與育幼、分配食物與築巢、守衛蜂巢，成熟後外出採集花蜜、花粉、水與樹脂。季節與群體需求也會調整分工。',source:'綠色和平蜜蜂科普',url:'https://www.greenpeace.org/taiwan/update/35923/'},
{cat:'ecology',tag:'蜜蜂生態',title:'蜜蜂如何傳遞蜜源位置？',keys:['跳舞','八字舞','溝通','蜜源','位置'],text:'採集蜂會用圓舞或搖擺舞傳遞蜜源資訊；舞蹈方向、角度與持續時間能讓同伴判斷方位與大致距離。',source:'綠色和平蜜蜂科普',url:'https://www.greenpeace.org/taiwan/update/35923/'},
{cat:'brand',tag:'陳家故事',title:'陳家蜂蜜是誰？',keys:['陳家','品牌','神農獎','歷史','文化館'],text:'陳家蜂蜜是屏東枋山三代蜂農品牌，養蜂逾 70 年。陳生章先生於 2003 年獲全國十大傑出農民神農獎；枋山文化館介紹蜂蜜從採集到收成的過程。',source:'陳家蜂蜜／屏東旅遊網',url:'https://www.i-pingtung.com/Pingtungfood/%E9%99%B3%E5%AE%B6%E8%9C%82%E8%9C%9C%E6%96%87%E5%8C%96%E9%A4%A8/%E6%9E%8B%E5%B1%B1%E9%84%89'},
{cat:'brand',tag:'陳家故事',title:'陳家蜂蜜有哪些蜜種？',keys:['產品','蜜種','龍眼蜜','冬蜜','百花蜜','荔枝蜜','梢楠蜜','蒲姜蜜'],text:'官方銷售網列有冬蜜、龍眼蜜、荔枝蜜、百花蜜、特級野蜂蜜、深山白蜜、梢楠蜜、苦楝蜜與蒲姜蜜等，實際品項隨花期與採收批次變動。',source:'陳家蜂蜜官方銷售網',url:'https://www.taiwanhoney.com/'},
{cat:'health',tag:'智慧養蜂研究',title:'AI 如何辨識死亡蜜蜂？',keys:['AI','YOLO','死亡辨識','智慧蜂箱','mAP','預警'],text:'陳家枋山蜂場的研究以防水蜂口取像、Jetson Nano 邊緣運算與 YOLOv9，區分自然老化與疑似神經毒性農藥相關型態。模型 mAP@0.5 達 0.937，並以即時儀表板與行動通知協助提早採樣；它是預警工具，不能取代化學檢驗與蜂群管理。',source:'Journal of Invertebrate Pathology 研究稿（2026）',url:'#death'},
{cat:'health',tag:'智慧養蜂研究',title:'如何自動監測蜂蟹蟎？',keys:['蜂蟹蟎','YOLOv7','影像辨識','82%','百里酚'],text:'屏科大研究改造傳統木箱並設置取像設備，以 YOLOv7 辨識健康蜂與感染蜂蟹蟎的蜜蜂，研究報告辨識準確率 82%。影像預警可減輕逐箱人工檢查負擔，但用藥與治療仍須依合法標示、溫度條件及專業建議。',source:'《蜂蟹蟎影像辨識與治療之研究》（2024）',url:'#library'},
{cat:'management',tag:'智慧養蜂研究',title:'智慧蜂箱有哪些功能？',keys:['智慧蜂箱','太陽能','Jetson Nano','攝影機','即時監測','Discord'],text:'研究架構以太陽能供電，4K 攝影機在蜂口取像，由 Jetson Nano 現場推論，再把結果傳至網頁儀表板並發送行動警示。研討會研究將目標分為活動監測、死亡分類、邊緣運算與異常早期預警。',source:'IWAIT 國際研討會研究（2026）',url:'#story'}
];
const builtInKnowledge=[...knowledge];
async function loadUploadedKnowledge(){
  try{
    const response=await fetch('/api/knowledge',{cache:'no-store'});
    if(!response.ok)throw new Error('API unavailable');
    const uploaded=await response.json();
    knowledge=[...builtInKnowledge,...uploaded];
    renderCards(librarySearch.value);
  }catch(error){
    console.info('目前使用內建知識庫；後端連線後會自動載入上傳資料。');
  }
}
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));const safeUrl=value=>String(value||'').startsWith('/uploads/')||String(value||'').startsWith('#')||/^https?:\/\//i.test(String(value||''))?String(value):'#';
const cards=document.querySelector('#cards');let filter='all';function renderCards(q=''){const s=q.trim().toLowerCase();cards.innerHTML=knowledge.filter(k=>(filter==='all'||k.cat===filter)&&(!s||(k.title+k.text+k.keys.join('')).toLowerCase().includes(s))).map(k=>`<article class="card reveal show"><small>${escapeHtml(k.tag)}</small><h3>${escapeHtml(k.title)}</h3><p>${escapeHtml(k.text)}</p><a href="${escapeHtml(safeUrl(k.url))}" ${String(k.url).startsWith('http')?'target="_blank" rel="noopener"':''}>來源：${escapeHtml(k.source)} ↗</a></article>`).join('')||'<p>目前找不到符合的知識，試試其他關鍵字。</p>'}renderCards();
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderCards(librarySearch.value)});librarySearch.oninput=e=>renderCards(e.target.value);
const synonymGroups=[['死亡','死掉','死很多','蜂屍','暴斃'],['吐舌','舌頭伸出','吻伸出','伸舌'],['餵食','餵糖','補餵','飼料'],['蜂蟹蟎','蟎蟲','蜂蟎','瓦蟎'],['蜂后','蜂王','女王蜂','失王'],['檢查','開箱','巡箱'],['結晶','變硬','凝固'],['真假','純不純','假蜜'],['中毒','農藥','噴藥'],['下雨','降雨','雨天'],['生病','疾病','不健康','異常']];
function normalizeQuestion(value){let text=String(value||'').toLowerCase().replace(/[\s，。！？、,.!?：:；;「」『』（）()]/g,'');synonymGroups.forEach(group=>{if(group.some(word=>text.includes(word)))text+=' '+group.join(' ')});return text}
function fuzzyScore(q,k){const haystack=normalizeQuestion([k.title,k.text,k.source,...(k.keys||[])].join(' '));let score=0;(k.keys||[]).forEach(key=>{if(q.includes(normalizeQuestion(key)))score+=8});if(q.includes(normalizeQuestion(k.title).replace(/[？?]/g,'')))score+=12;const compact=q.replace(/\s/g,'');const grams=new Set();for(let i=0;i<compact.length-1;i++)grams.add(compact.slice(i,i+2));grams.forEach(gram=>{if(haystack.includes(gram))score+=2});return score}
function answer(q){const normalized=normalizeQuestion(q);let ranked=knowledge.map(k=>({k,score:fuzzyScore(normalized,k)})).sort((a,b)=>b.score-a.score);if(!ranked[0]||ranked[0].score<2)return `目前的在地知識庫還找不到合適答案。可以用日常說法再描述一次，例如「蜜蜂突然死很多」、「蜂蜜為什麼變硬」或「最近可以開箱嗎」。\n\n若是蜂群緊急異常，請聯絡所在地農政或動物防疫單位。`;const matches=ranked.filter(item=>item.score>=Math.max(4,ranked[0].score*.65)).slice(0,2);return matches.map(({k},index)=>`${index?`相關資料：${k.title}\n`:''}${k.text}\n\n資料來源：${k.source}`).join('\n\n——\n\n')}
function addMsg(text,type='ai'){const el=document.createElement('div');el.className='msg '+type;el.innerHTML=type==='ai'?`<span>陳</span><div>${escapeHtml(text)}</div>`:`<div>${escapeHtml(text)}</div>`;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}askForm.onsubmit=e=>{e.preventDefault();const q=question.value.trim();if(!q)return;addMsg(q,'user');question.value='';setTimeout(()=>addMsg(answer(q)),350)};document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{question.value=b.textContent;askForm.requestSubmit()});clearChat.onclick=()=>messages.innerHTML='<div class="msg ai"><span>陳</span><div>對話已清除。想問哪一項養蜂問題？</div></div>';
const dx={natural:['日常觀察','少量、分散、持續發生','巢門周邊偶見少量完整蜂屍，且採集與出勤正常，多屬工蜂自然汰換。重點不是單隻外觀，而是每日數量趨勢。',['固定時間記錄蜂屍數量','觀察是否突然增加或聚集','同步確認存糧與出勤'],'先記錄趨勢，不只看一隻蜜蜂。'],poison:['立即警戒','短時間大量、突然倒地','若伴隨抽搐、顫抖、失向，且附近近期施藥，應保留樣本並通報；外觀仍無法證實農藥中毒。',['戴手套採樣並冷藏','記錄時間、天氣與施藥情形','聯絡農政或防疫單位'],'先保存證據，不自行猜測或投藥。'],pest:['加強檢查','持續增加、伴隨異常症狀','爬蜂、畸形翅或蜂勢衰弱，可能涉及蜂蟹蟎、病毒等多重因素。',['檢查幼蟲、巢脾及蟎量','隔離並清潔共用蜂具','尋求專業診斷'],'症狀會重疊，應先檢測。'],cold:['優先處置','空巢缺糧、蜂頭朝內','蜜源中斷、存糧不足或低溫使蜂球無法移動，可能造成飢餓或失溫。',['檢查封蓋蜜與花粉','確認蜂箱潮濕與受風','依蜂勢進行適當補飼'],'先確保保溫與食物可及。'],queen:['追蹤蜂況','新蜂減少、秩序改變','蜂后死亡或產卵異常會讓蜂群補充中斷，常見無卵、雄蜂卵或蜂勢逐步下降。',['查看卵蟲與產卵圈','確認王台與蜂后','避免頻繁開箱干擾'],'以完整巢脾與數日趨勢判讀。']};document.querySelectorAll('[data-dx]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-dx]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=dx[b.dataset.dx];dxLevel.textContent=d[0];dxTitle.textContent=d[1];dxBody.textContent=d[2];dxList.innerHTML=d[3].map(x=>`<li>${x}</li>`).join('');dxAction.textContent=d[4]});
const codeText=c=>c===0?'晴朗':c<=3?'多雲':c<=48?'有霧':c<=67?'有雨':c<=82?'陣雨':c<=99?'雷雨':'天氣變化';async function loadWeather(){try{const u='https://api.open-meteo.com/v1/forecast?latitude=22.26&longitude=120.65&current=temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FTaipei&forecast_days=5';const d=await fetch(u).then(r=>r.json()),c=d.current;temperature.textContent=Math.round(c.temperature_2m);humidity.textContent=c.relative_humidity_2m+'%';wind.textContent=Math.round(c.wind_speed_10m)+' km/h';rain.textContent=c.precipitation+' mm';weatherText.textContent=codeText(c.weather_code);weatherIcon.textContent=c.weather_code<=3?'☀':'☂';let a='適合外部觀察',reason='氣候尚可，仍先觀察蜂群出勤。';if(c.precipitation>0||c.relative_humidity_2m>90){a='不建議長時間開箱';reason='降雨或高濕度可能使蜂巢受潮。'}else if(c.wind_speed_10m>25){a='留意強風，避免開箱';reason='風勢較強會干擾飛行與保溫。'}else if(c.temperature_2m<15||c.temperature_2m>35){a='減少擾動蜂群';reason='溫度較極端，優先維持蜂群穩定。'}beeAdvice.textContent=a;beeReason.textContent=reason;forecast.innerHTML=d.daily.time.map((x,i)=>`<div><b>${new Date(x).toLocaleDateString('zh-TW',{weekday:'short'})}</b><br>${codeText(d.daily.weather_code[i])}<br><small>${Math.round(d.daily.temperature_2m_min[i])}°—${Math.round(d.daily.temperature_2m_max[i])}° · 雨 ${d.daily.precipitation_probability_max[i]}%</small></div>`).join('')}catch(e){weatherText.textContent='無法取得即時天氣';beeAdvice.textContent='請先查看現場天候';beeReason.textContent='網路恢復後將自動更新。'}}loadWeather();
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));document.querySelector('.menu').onclick=()=>document.querySelector('nav').classList.toggle('open');
const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='manifest.webmanifest';document.head.appendChild(manifest);const theme=document.createElement('meta');theme.name='theme-color';theme.content='#0d2d24';document.head.appendChild(theme);const iosCapable=document.createElement('meta');iosCapable.name='apple-mobile-web-app-capable';iosCapable.content='yes';document.head.appendChild(iosCapable);const iosStatus=document.createElement('meta');iosStatus.name='apple-mobile-web-app-status-bar-style';iosStatus.content='black-translucent';document.head.appendChild(iosStatus);const iosTitle=document.createElement('meta');iosTitle.name='apple-mobile-web-app-title';iosTitle.content='陳家養蜂智庫';document.head.appendChild(iosTitle);const touchIcon=document.createElement('link');touchIcon.rel='apple-touch-icon';touchIcon.href='assets/hero-honey.png';document.head.appendChild(touchIcon);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));loadUploadedKnowledge();
