import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const password=Deno.env.get('ADMIN_PASSWORD')||'7771',secret=Deno.env.get('SESSION_SECRET')||'chen-honey-secret';
const bytes=(v:string)=>new TextEncoder().encode(v);const b64=(v:Uint8Array)=>btoa(String.fromCharCode(...v)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sign(v:string){const k=await crypto.subtle.importKey('raw',bytes(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',k,bytes(v))))}
async function newToken(){const p=b64(bytes(JSON.stringify({exp:Date.now()+28800000})));return p+'.'+await sign(p)}
async function authorized(req:Request){const [p,s]=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').split('.');if(!p||!s||await sign(p)!==s)return false;try{return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/'))).exp>Date.now()}catch{return false}}
const item=(r:any)=>({id:r.id,cat:r.cat,tag:r.tag,title:r.title,keys:r.keys,text:r.text,source:r.source,url:r.url,fileName:r.file_name,mimeType:r.mime_type,size:r.size,createdAt:r.created_at});
Deno.serve(async(req)=>{try{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});const requestUrl=new URL(req.url),action=requestUrl.searchParams.get('action'),id=requestUrl.searchParams.get('id');
if(req.method==='POST'&&action==='login'){const b=await req.json();return String(b.password||'')===password?json({token:await newToken()}):json({error:'密碼錯誤'},401)}
if(req.method==='GET'){const {data,error}=await db.from('knowledge').select('*').order('created_at',{ascending:false});if(error)throw error;return json((data||[]).map(item))}
if(!await authorized(req))return json({error:'請重新登入'},401);
if(req.method==='POST'){const f=await req.formData(),file=f.get('file');if(!(file instanceof File))return json({error:'請選擇檔案'},400);const path=`${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await db.storage.from('knowledge-files').upload(path,file,{contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const title=String(f.get('title')||file.name).trim(),summary=String(f.get('summary')||'').trim(),ext=file.name.split('.').pop()?.toLowerCase()||'';let extracted='';if(file.type.startsWith('text/')||['txt','md','csv','json','html','htm','xml','log'].includes(ext))extracted=(await file.text()).replace(/\s+/g,' ').slice(0,12000);const keys=String(f.get('keywords')||'').split(/[,，、\n]/).map(x=>x.trim()).filter(Boolean),url=db.storage.from('knowledge-files').getPublicUrl(path).data.publicUrl;const row={cat:String(f.get('category')||'management'),tag:String(f.get('tag')||'後台新增'),title,keys:[...new Set([...keys,...title.split(/\s+/)])],text:summary||extracted||`已上傳檔案：${file.name}`,source:String(f.get('source')||file.name),url,file_name:file.name,mime_type:file.type,size:file.size,storage_path:path};const added=await db.from('knowledge').insert(row).select().single();if(added.error){await db.storage.from('knowledge-files').remove([path]);throw added.error}return json(item(added.data),201)}
if(req.method==='DELETE'&&id){const found=await db.from('knowledge').select('storage_path').eq('id',id).single(),removed=await db.from('knowledge').delete().eq('id',id);if(removed.error)throw removed.error;if(found.data?.storage_path)await db.storage.from('knowledge-files').remove([found.data.storage_path]);return new Response(null,{status:204,headers:cors})}return json({error:'不支援的操作'},405)}catch(e){console.error(e);return json({error:'伺服器處理失敗'},500)}});
