const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, content-type, apikey','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const base=Deno.env.get('SUPABASE_URL')||'',serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const password=Deno.env.get('ADMIN_PASSWORD')||'7771',secret=Deno.env.get('SESSION_SECRET')||'chen-honey-secret';
const serviceHeaders={apikey:serviceKey,Authorization:`Bearer ${serviceKey}`};
const bytes=(v:string)=>new TextEncoder().encode(v);const b64=(v:Uint8Array)=>btoa(String.fromCharCode(...v)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sign(v:string){const k=await crypto.subtle.importKey('raw',bytes(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',k,bytes(v))))}
async function newToken(){const p=b64(bytes(JSON.stringify({exp:Date.now()+28800000})));return p+'.'+await sign(p)}
async function authorized(req:Request){const [p,s]=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').split('.');if(!p||!s||await sign(p)!==s)return false;try{return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/'))).exp>Date.now()}catch{return false}}
const item=(r:any)=>({id:r.id,cat:r.cat,tag:r.tag,title:r.title,keys:r.keys,text:r.text,source:r.source,url:r.url,fileName:r.file_name,mimeType:r.mime_type,size:r.size,createdAt:r.created_at});
async function rest(path:string,init:RequestInit={}){const headers=new Headers(init.headers);headers.set('apikey',serviceKey);headers.set('Authorization',`Bearer ${serviceKey}`);const response=await fetch(base+'/rest/v1/'+path,{...init,headers});if(!response.ok)throw new Error(await response.text());return response}
Deno.serve(async(req)=>{try{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!base||!serviceKey)throw new Error('Supabase environment unavailable');const u=new URL(req.url),action=u.searchParams.get('action'),id=u.searchParams.get('id');
if(req.method==='POST'&&action==='login'){const b=await req.json();return String(b.password||'')===password?json({token:await newToken()}):json({error:'密碼錯誤'},401)}
if(req.method==='GET'){const response=await rest('knowledge?select=*&order=created_at.desc');return json((await response.json()).map(item))}
if(!await authorized(req))return json({error:'請重新登入'},401);
if(req.method==='POST'){const f=await req.formData(),file=f.get('file');if(!(file instanceof File))return json({error:'請選擇檔案'},400);const path=`${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const upload=await fetch(base+'/storage/v1/object/knowledge-files/'+path,{method:'POST',headers:{...serviceHeaders,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!upload.ok)throw new Error(await upload.text());const title=String(f.get('title')||file.name).trim(),summary=String(f.get('summary')||'').trim(),ext=file.name.split('.').pop()?.toLowerCase()||'';let extracted='';if(file.type.startsWith('text/')||['txt','md','csv','json','html','htm','xml','log'].includes(ext))extracted=(await file.text()).replace(/\s+/g,' ').slice(0,12000);const keys=String(f.get('keywords')||'').split(/[,，、\n]/).map(x=>x.trim()).filter(Boolean),fileUrl=base+'/storage/v1/object/public/knowledge-files/'+path;const row={cat:String(f.get('category')||'management'),tag:String(f.get('tag')||'後台新增'),title,keys:[...new Set([...keys,...title.split(/\s+/)])],text:summary||extracted||`已上傳檔案：${file.name}`,source:String(f.get('source')||file.name),url:fileUrl,file_name:file.name,mime_type:file.type,size:file.size,storage_path:path};let added;try{const response=await rest('knowledge',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(row)});added=(await response.json())[0]}catch(error){await fetch(base+'/storage/v1/object/knowledge-files/'+path,{method:'DELETE',headers:serviceHeaders});throw error}return json(item(added),201)}
if(req.method==='DELETE'&&id){const found=await rest('knowledge?id=eq.'+encodeURIComponent(id)+'&select=storage_path'),rows=await found.json();await rest('knowledge?id=eq.'+encodeURIComponent(id),{method:'DELETE'});if(rows[0]?.storage_path)await fetch(base+'/storage/v1/object/knowledge-files/'+rows[0].storage_path,{method:'DELETE',headers:serviceHeaders});return new Response(null,{status:204,headers:cors})}return json({error:'不支援的操作'},405)}catch(e){console.error(e);return json({error:'伺服器處理失敗'},500)}});
